TIN_BookApp/tin_pja_bookapp/Controllers/AuthorsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using tin_pja_bookapp.DAL;
using tin_pja_bookapp.Models;

namespace tin_pja_bookapp.Controllers
{
    public class AuthorsController : Controller
    {
        private BooksDb db = new BooksDb();

        // GET: Authors
        public ActionResult Index()
        {
            return View(db.Authors.ToList());
        }

        // GET: Authors/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AuthorViewModel authorViewModel = db.Authors.Find(id);
            if (authorViewModel == null)
            {
                return HttpNotFound();
            }
            return View(authorViewModel);
        }

        // GET: Authors/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Authors/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IdAuthor,Name,Description")] AuthorViewModel authorViewModel)
        {
            if (ModelState.IsValid)
            {
                db.Authors.Add(authorViewModel);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(authorViewModel);
        }

        // GET: Authors/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AuthorViewModel authorViewModel = db.Authors.Find(id);
            if (authorViewModel == null)
            {
                return HttpNotFound();
            }
            return View(authorViewModel);
        }

        // POST: Authors/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IdAuthor,Name,Description")] AuthorViewModel authorViewModel)
        {
            if (ModelState.IsValid)
            {
                db.Entry(authorViewModel).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(authorViewModel);
        }

        // GET: Authors/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AuthorViewModel authorViewModel = db.Authors.Find(id);
            if (authorViewModel == null)
            {
                return HttpNotFound();
            }
            return View(authorViewModel);
        }

        // POST: Authors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            AuthorViewModel authorViewModel = db.Authors.Find(id);
            db.Authors.Remove(authorViewModel);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TIN_BookApp/tin_pja_bookapp/Controllers/BooksController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using tin_pja_bookapp.DAL;
using tin_pja_bookapp.Models;

namespace tin_pja_bookapp.Controllers
{
    public class BooksController : Controller
    {
        private BooksDb db = new BooksDb();

        // GET: Books
        public ActionResult Index()
        {
            var books = db.Books.Include(b => b.CurrentAuthor);

            return View(books.ToList());
        }

        // GET: Books/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            BookViewModel book = db.Books
              .Include(i => i.CurrentAuthor)
              .SingleOrDefault(x => x.IdBook == id);

            if (book == null)
            {
                return HttpNotFound();
            }
            return View(book);
        }

        // GET: Books/Create
        public ActionResult Create()
        {
            ViewBag.CurrentIdAuthor = new SelectList(db.Authors, "IdAuthor", "Name");
            return View();
        }

        // POST: Books/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IdBook,Name,Description,Image,CurrentIdAuthor")] BookViewModel bookViewModel)
        {
            if (ModelState.IsValid)
            {
                db.Books.Add(bookViewModel);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CurrentIdAuthor = new SelectList(db.Authors, "IdAuthor", "Name", bookViewModel.CurrentIdAuthor);
            return View(bookViewModel);
        }

        // GET: Books/Edit/5
        [Authorize]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BookViewModel bookViewModel = db.Books.Find(id);
            if (bookViewModel == null)
            {
                return HttpNotFound();
            }
            ViewBag.CurrentIdAuthor = new SelectList(db.Authors, "IdAuthor", "Name", bookViewModel.CurrentIdAuthor);
            return View(bookViewModel);
        }

        // POST: Books/Edit/5
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IdBook,Name,Description,Image,CurrentIdAuthor")] BookViewModel bookViewModel)
        {
            if (ModelState.IsValid)
            {
                db.Entry(bookViewModel).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CurrentIdAuthor = new SelectList(db.Authors, "IdAuthor", "Name", bookViewModel.CurrentIdAuthor);
            return View(bookViewModel);
        }

        // GET: Books/Delete/5
        [Authorize]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BookViewModel book = db.Books
              .Include(i => i.CurrentAuthor)
              .SingleOrDefault(x => x.IdBook == id);

            if (book == null)
            {
                return HttpNotFound();
            }
            return View(book);
        }

        // POST: Books/Delete/5
        [Authorize]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            BookViewModel bookViewModel = db.Books.Find(id);
            db.Books.Remove(bookViewModel);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TIN_BookApp/tin_pja_bookapp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css?family=Cinzel" rel="stylesheet">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

   

</head>
<body>

    <div class="field">
        <img src="https://www.weareinnovative.co.uk/wp-content/uploads/2015/06/got2.jpg" align="middle">

        <div class="navbar">
            <ul>
                <h2>
                    @Html.ActionLink("LibLighthouse", "Index", "Home")
                    @Html.ActionLink("Literatura", "Index", "Books")
                    @Html.ActionLink("Autorzy", "Index", "Authors")
                    @Html.Partial("_LoginPartial")
                    <h2>
            </ul>
        </div>

        <h1>LibLighthouse</h1>
        <div class="textfield">
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam tincidunt mi lorem, non consectetur libero dictum quis. Vestibulum risus sapien, rhoncus ut justo eu, luctus luctus neque. Quisque mi ex, tincidunt lacinia molestie feugiat, interdum quis magna. Ut non accumsan sem. Vestibulum sodales magna ac justo hendrerit cursus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Fusce ac maximus metus. Ut luctus mi nec turpis viverra lobortis. Sed ornare vestibulum turpis id aliquet. Nam ac aliquet turpis. Suspendisse non facilisis urna. Nulla in pretium nisi. Proin ut scelerisque est. Sed at porttitor augue, lacinia dictum ipsum. Nam ac leo consequat, tincidunt urna vitae, vulputate velit. Maecenas quis nulla ultricies, vehicula arcu et, tempor dolor.
        </div>

        @RenderBody()

        <div class="footer">
            LibLighthouse Company Sp. z.o.o.<br />
            created by Marcin Krupa s13711
        </div>
    </div>

    @RenderSection("scripts", required: false)


    <script type="text/javascript" src="~/Scripts/validation.js"></script>
</body>
</html>